package controller;





import dao.ClienteDAOImpl;
import model.Administrador;
import model.Cliente;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import dao.AdministradorDAOImpl;
import estructuras.Cola;
import estructuras.ListaDoble;


public class frmLogin extends javax.swing.JFrame {
    
    ClienteDAOImpl clienteReposi = new ClienteDAOImpl();
    AdministradorDAOImpl adminReposi = new AdministradorDAOImpl();
    private Cola<Cliente> clientes = new Cola<>();
    private ListaDoble<Administrador> administradores = new ListaDoble<>();
    
    
    public frmLogin() {
        initComponents();//iniciar los componentes
        this.setLocationRelativeTo(null);//centrar la interfaz
        clientes = clienteReposi.leerTodo();
        administradores = adminReposi.leerTodo();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jpfContrasena = new javax.swing.JPasswordField();
        jrbAdministrador = new javax.swing.JRadioButton();
        jrbAlumno = new javax.swing.JRadioButton();
        btnIngresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Contraseña:");

        jtfUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jpfContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfContrasenaActionPerformed(evt);
            }
        });

        btnGrupo.add(jrbAdministrador);
        jrbAdministrador.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jrbAdministrador.setText("Administrador");

        btnGrupo.add(jrbAlumno);
        jrbAlumno.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jrbAlumno.setText("Cliente");
        jrbAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAlumnoActionPerformed(evt);
            }
        });

        btnIngresar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logeo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jpfContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jrbAdministrador)
                .addGap(77, 77, 77)
                .addComponent(jrbAlumno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIngresar)
                .addGap(172, 172, 172))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jpfContrasena))
                    .addComponent(jLabel3))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbAdministrador)
                    .addComponent(jrbAlumno))
                .addGap(38, 38, 38)
                .addComponent(btnIngresar)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if(verificarLlenadoCampos()) {
            boolean encontrado = false;
            String usuario = jtfUsuario.getText();
            String contrasena = String.valueOf(jpfContrasena.getPassword());
            if(jrbAdministrador.isSelected()) {
                for(Administrador auxiliar : administradores) {
                    if(auxiliar.getUsuario().equals(usuario) && auxiliar.getContrasena().equals(contrasena)) {
                        encontrado = true;
                        this.dispose();//cerrar la interfaz login
                        frmPrincipalAdministrador admin = new frmPrincipalAdministrador(auxiliar);
                        admin.setVisible(true);
                    }
                }
            } else {
                for(Cliente auxiliar : clientes) {
                    if(auxiliar.getUsuario().equals(usuario) && auxiliar.getContrasena().equals(contrasena)) {
                        encontrado = true;
                        this.dispose();//cerrar la interfaz login
                        frmPrincipalCliente clie = new frmPrincipalCliente(auxiliar);
                        clie.setVisible(true);
                    }
                }
                
            }
            if(!encontrado) {
                JOptionPane.showMessageDialog(rootPane,
                        "No existe tal usuario",
                        "Mensaje",
                        JOptionPane.WARNING_MESSAGE);
            }
            
        } else{ 
            JOptionPane.showMessageDialog(rootPane,
                    "Debe completar todos los campos",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    public boolean verificarLlenadoCampos() {
        boolean vacio;
        vacio = jtfUsuario.getText().equals("") || String.valueOf(jpfContrasena.getPassword()).equals("")
                || (!jrbAdministrador.isSelected() && !jrbAlumno.isSelected() );
        
        if(vacio) {
            return false;
        } else {
            return true;
        }
    }
    
    private void jpfContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfContrasenaActionPerformed

    private void jrbAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrupo;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jpfContrasena;
    private javax.swing.JRadioButton jrbAdministrador;
    private javax.swing.JRadioButton jrbAlumno;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
