package controller;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import model.Cliente;
import model.Vuelo;
import model.Boleto;
import java.util.*;
import javax.swing.JOptionPane;
import dao.VueloDAOImpl;
import dao.BoletoDAOImpl;

public class frmPrincipalCliente extends javax.swing.JFrame {
    
    BoletoDAOImpl boletoReposi = new BoletoDAOImpl();
    VueloDAOImpl vueloreposi = new VueloDAOImpl();
    private List<Boleto> boletos;
    private List<Vuelo> vuelos;
    private Cliente cliente;
    /**
     * Creates new form frmInicioAlumno
     */
    public frmPrincipalCliente(Cliente logeado) {
        initComponents();
        //this.setExtendedState(frmPrincipalAlumno.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        this.setTitle("Sistema de Compra");
        cliente = logeado;
        vuelos = vueloreposi.readAll();
        boletos = new ArrayList<>();
        
    }

    private frmPrincipalCliente() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuInformacion = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        cutMenuItem1 = new javax.swing.JMenuItem();
        mnuVuelo = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        mnuReporte = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fisi2.jpg"))); // NOI18N
        desktopPane.add(jLabel1);
        jLabel1.setBounds(470, 360, 224, 60);

        mnuInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/informacion.png"))); // NOI18N
        mnuInformacion.setMnemonic('e');
        mnuInformacion.setText("Mi Información");
        mnuInformacion.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        cutMenuItem.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        cutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/informacion.png"))); // NOI18N
        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Mi perfil");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        mnuInformacion.add(cutMenuItem);

        cutMenuItem1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        cutMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/informacion.png"))); // NOI18N
        cutMenuItem1.setMnemonic('t');
        cutMenuItem1.setText("Cambiar contraseña");
        cutMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItem1ActionPerformed(evt);
            }
        });
        mnuInformacion.add(cutMenuItem1);

        menuBar.add(mnuInformacion);

        mnuVuelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/avion.png"))); // NOI18N
        mnuVuelo.setMnemonic('h');
        mnuVuelo.setText("Vuelos");
        mnuVuelo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        contentMenuItem.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        contentMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boleto.png"))); // NOI18N
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Realizar compra");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        mnuVuelo.add(contentMenuItem);

        aboutMenuItem.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/horario.png"))); // NOI18N
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Programación de vuelos");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        mnuVuelo.add(aboutMenuItem);

        menuBar.add(mnuVuelo);

        mnuReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte.png"))); // NOI18N
        mnuReporte.setText("Reportes");
        mnuReporte.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte.png"))); // NOI18N
        jMenuItem1.setText("Reporte de boleto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuReporte.add(jMenuItem1);

        menuBar.add(mnuReporte);

        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.jpg"))); // NOI18N
        mnuSalir.setText("Salir");
        mnuSalir.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });

        jMenuItem3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.jpg"))); // NOI18N
        jMenuItem3.setText("Cerrar sesión");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnuSalir.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.jpg"))); // NOI18N
        jMenuItem4.setText("Finalizar programa");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnuSalir.add(jMenuItem4);

        menuBar.add(mnuSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    public boolean CompraYaRealizada() {
        boolean faltaComprar = true;
        
            boletos = boletoReposi.readAll();
        
        for(Boleto boleto : boletos) {
            if(boleto.getUsuariocliente().equals(cliente.getUsuario())) {
                faltaComprar = false;
            }
        }
        return !faltaComprar;
    }
    
    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
       frmProgramacionVuelos prog = new frmProgramacionVuelos();
       prog.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        frmPerfilCliente perf = new frmPerfilCliente(cliente);
       perf.setVisible(true);
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
        frmLogin log = new frmLogin();
        log.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        if(CompraYaRealizada()) {
            JOptionPane.showMessageDialog(rootPane,
                    "Ud. ya realizó su compra",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            frmBoleto m = new frmBoleto(vuelos, cliente);
           m.setVisible(true);
        }
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JOptionPane.showMessageDialog(rootPane,
                "Gracias por usar nuestro sistema",
                "Mensaje",
                JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if(CompraYaRealizada()) {
            frmReporteBoleto rep = new frmReporteBoleto(cliente);
            rep.setVisible(true);
            
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Ud. debe realizar una compra",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void cutMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItem1ActionPerformed
        frmPerfilCambiarcontraseña con=new frmPerfilCambiarcontraseña(cliente);
        con.setVisible(true);
    }//GEN-LAST:event_cutMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipalCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem cutMenuItem1;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuInformacion;
    private javax.swing.JMenu mnuReporte;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JMenu mnuVuelo;
    // End of variables declaration//GEN-END:variables

}
